#!/usr/bin/env bash

DIR="$HOME/.recollect"

case "$1" in
  start)
    cd "$DIR"
    docker compose up -d
    ;;
  stop)
    cd "$DIR"
    docker compose down
    ;;
  restart)
    cd "$DIR"
    docker compose restart
    ;;
  update)
    cd "$DIR"
    git pull
    docker compose up -d --build
    ;;
  *)
    echo "Recollect CLI"
    echo "Usage:"
    echo "  recollect start"
    echo "  recollect stop"
    echo "  recollect restart"
    echo "  recollect update"
    ;;
esac